# Generated by Django 6.0.6 on 2026-06-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
